name: Build Python Wheel

on:
  push:
    # Build on pushes to the default branch and on tag pushes
    branches:
      - master
    tags:
      - 'v*'
      
jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: pip install build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: corsair-wheel
          path: dist/*.whl

      - name: Upload wheel to release (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}